spring.application.name=kickoff-notifications
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/kickoff_notifications?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.jackson.default-property-inclusion=non_null
spring.jackson.deserialization.read-unknown-enum-values-as-null=true
